package company.model;
// default package
// Generated May 10, 2015 12:15:33 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Admin generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "admin")
public class Admin implements java.io.Serializable {

	private Integer adminId;
	private String name;
	private Integer birthday;
	private String email;
	private String gender;
	private String phone;
	private String password;
	private Set<Manager> managers = new HashSet<Manager>(0);

	public Admin() {
	}

	public Admin(String name, Integer birthday, String email, String gender,
			String phone, String password, Set<Manager> managers) {
		this.name = name;
		this.birthday = birthday;
		this.email = email;
		this.gender = gender;
		this.phone = phone;
		this.password = password;
		this.managers = managers;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ADMIN_ID", unique = true, nullable = false)
	public Integer getAdminId() {
		return this.adminId;
	}

	public void setAdminId(Integer adminId) {
		this.adminId = adminId;
	}

	@Column(name = "NAME", length = 30)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "BIRTHDAY")
	public Integer getBirthday() {
		return this.birthday;
	}

	public void setBirthday(Integer birthday) {
		this.birthday = birthday;
	}

	@Column(name = "EMAIL", length = 50)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "GENDER", length = 5)
	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	@Column(name = "PHONE", length = 15)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "PASSWORD", length = 20)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "admin")
	public Set<Manager> getManagers() {
		return this.managers;
	}

	public void setManagers(Set<Manager> managers) {
		this.managers = managers;
	}

}
