package company.model;
// default package
// Generated May 19, 2015 9:38:52 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Message generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "message")
public class Message implements java.io.Serializable {

	private Integer messageId;
	private String title;
	private String content;
	private String date;
	private String ftype;
	private int fid;
	private String ttype;
	private int tid;
	private String status;

	public Message() {
	}

	public Message(String content, String date, String ftype, int fid,
			String ttype, int tid, String status) {
		this.content = content;
		this.date = date;
		this.ftype = ftype;
		this.fid = fid;
		this.ttype = ttype;
		this.tid = tid;
		this.status = status;
	}

	public Message(String title, String content, String date, String ftype,
			int fid, String ttype, int tid, String status) {
		this.title = title;
		this.content = content;
		this.date = date;
		this.ftype = ftype;
		this.fid = fid;
		this.ttype = ttype;
		this.tid = tid;
		this.status = status;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "MESSAGE_ID", unique = true, nullable = false)
	public Integer getMessageId() {
		return this.messageId;
	}

	public void setMessageId(Integer messageId) {
		this.messageId = messageId;
	}

	@Column(name = "TITLE", length = 30)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "CONTENT", nullable = false, length = 100)
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Column(name = "DATE", nullable = false, length = 100)
	public String getDate() {
		return this.date;
	}

	public void setDate(String date) {
		this.date = date;
	}

	@Column(name = "FTYPE", nullable = false, length = 10)
	public String getFtype() {
		return this.ftype;
	}

	public void setFtype(String ftype) {
		this.ftype = ftype;
	}

	@Column(name = "FID", nullable = false)
	public int getFid() {
		return this.fid;
	}

	public void setFid(int fid) {
		this.fid = fid;
	}

	@Column(name = "TTYPE", nullable = false, length = 10)
	public String getTtype() {
		return this.ttype;
	}

	public void setTtype(String ttype) {
		this.ttype = ttype;
	}

	@Column(name = "TID", nullable = false)
	public int getTid() {
		return this.tid;
	}

	public void setTid(int tid) {
		this.tid = tid;
	}

	@Column(name = "STATUS", nullable = false, length = 10)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

}
