package company.model;
// default package
// Generated May 19, 2015 9:38:52 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Notice generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "notice", catalog = "company")
public class Notice implements java.io.Serializable {

	private Integer noticeId;
	private String title;
	private String content;
	private String date;

	public Notice() {
	}

	public Notice(String content, String date) {
		this.content = content;
		this.date = date;
	}

	public Notice(String title, String content, String date) {
		this.title = title;
		this.content = content;
		this.date = date;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "NOTICE_ID", unique = true, nullable = false)
	public Integer getNoticeId() {
		return this.noticeId;
	}

	public void setNoticeId(Integer noticeId) {
		this.noticeId = noticeId;
	}

	@Column(name = "TITLE", length = 30)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "CONTENT", nullable = false, length = 100)
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Column(name = "DATE", nullable = false, length = 100)
	public String getDate() {
		return this.date;
	}

	public void setDate(String date) {
		this.date = date;
	}

}
