package company.model;
// default package
// Generated May 10, 2015 12:15:33 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.OrderBy;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Signin generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "signin")
public class Signin implements java.io.Serializable {

	private Integer signinId;
	private Employee employee;
	private String date;
	private String time;
	private String status;

	public Signin() {
	}

	public Signin(Employee employee, String time, String status) {
		this.employee = employee;
		this.time = time;
		this.status = status;
	}

	public Signin(Employee employee, String date, String time, String status) {
		this.employee = employee;
		this.date = date;
		this.time = time;
		this.status = status;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "SIGNIN_ID", unique = true, nullable = false)
	public Integer getSigninId() {
		return this.signinId;
	}

	public void setSigninId(Integer signinId) {
		this.signinId = signinId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EMPLOYEE_ID", nullable = false)
	public Employee getEmployee() {
		return this.employee;
	}

	public void setEmployee(Employee employee) {
		this.employee = employee;
	}

	@Column(name = "DATE", length = 30)
	@OrderBy
	public String getDate() {
		return this.date;
	}

	public void setDate(String date) {
		this.date = date;
	}

	@Column(name = "TIME", nullable = false, length = 100)
	public String getTime() {
		return this.time;
	}

	public void setTime(String time) {
		this.time = time;
	}

	@Column(name = "STATUS", nullable = false, length = 10)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

}
